// src/routes/cas/login.tsx
import { useSuspenseQuery } from "@tanstack/react-query"
import { createRoute } from "@tanstack/react-router"
import { type } from "arktype"
import { useState } from "react"
import { accountsDataOptions, api } from "@/client.ts"
import AccountChooser from "@/components/AccountChooser.tsx"
import type { Account } from "@/db/schema.ts"
import { queryClient } from "@/queryClient.tsx"
import { rootRoute } from "@/routes/__root.tsx"

const casLoginSearchSchema = type({
	service: "string",
})

export const casLoginRoute = createRoute({
	getParentRoute: () => rootRoute,
	path: "/cas/login",
	component: CasLogin,
	validateSearch: casLoginSearchSchema,
	loader: () => queryClient.ensureQueryData(accountsDataOptions),
})

function CasLogin() {
	const { service } = casLoginRoute.useSearch()
	const { data: accounts } = useSuspenseQuery(accountsDataOptions)
	const [err, setErr] = useState<string | null>(null)

	const onSelectedAccount = (account: Account) => {
		api.cas.authenticate
			.post({
				service,
				userId: account.id!,
			})
			.then(({ error, data: ticket }) => {
				if (error) {
					setErr(error.value.message!)
					return
				}
				window.location.href = `${service}?ticket=${ticket.ticket}`
			})
	}

	return (
		<div className="container mx-auto p-8">
			{err ? <p className="text-red-500 text-center">{err}</p> : null}

			<h1 className="text-2xl font-bold text-center">CAS Authentication</h1>
			<p className="text-lg text-center">
				Authenticating to CAS service{" "}
				<a
					href={service}
					className="underline text-blue-500"
					target="_blank"
					rel="noopener noreferrer"
				>
					{service}
				</a>
			</p>

			<p className="text-gray-500 text-center">
				Select a user to authenticate as...
			</p>

			<AccountChooser accounts={accounts} onSelectAccount={onSelectedAccount} />
		</div>
	)
}

// src/routes/cas/login/+page.svelte
<script lang="ts">
	import {enhance} from '$app/forms'
	import {LoaderCircle} from 'lucide-svelte'
	import Button from '$lib/components/Button.svelte'

	let {data, form} = $props()
	let canSelect = $state(true)
	let loadingAccountId = $state<string | null>(null)
</script>

{#if form?.error}
    <p class="text-red-500 text-center">{form.error}</p>
{/if}

<h1 class="text-2xl font-bold text-center">CAS Authentication</h1>
<p class="text-lg text-center">
    Authenticating to CAS service
    <a
            href={data.service}
            class="underline text-nas-purple-500"
            target="_blank"
            rel="noopener noreferrer external"
    >
        {data.service}
    </a>
</p>

<p class="text-gray-500 text-center">Select a user to authenticate as...</p>

<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 place-content-center mt-4">
    {#each data.accounts as account (account.id)}
        <div class="bg-nas-purple-100 border border-nas-purple p-4">
            <h2 class="text-xl font-semibold">{account.name}</h2>
            <p class="text-nas-purple-700">@{account.username}</p>
            <div class="p-6 pt-4">
                <form
                        method="POST"
                        action="?/authenticate&service={data.service}"
                        use:enhance={() => {
							canSelect = false;
							loadingAccountId = account.id;
							return async ({ update }) => {
								await update();
								canSelect = true;
								loadingAccountId = null;
							};
						}}
                >
                    <input type="hidden" name="accountId" value={account.id} />
                    <Button
                            type="submit"
                            class="w-full text-sm font-semibold py-2 px-4"
                            disabled={!canSelect}
                    >
                        {#if loadingAccountId === account.id}
                            <LoaderCircle class="animate-spin mx-auto" />
                        {:else}
                            Select
                        {/if}
                    </Button>
                </form>
            </div>
        </div>
    {/each}
</div>

<svelte:head>
    <title>CAS Authentication</title>
</svelte:head>
